#ifndef HAMSTERFILER_VERSION_H
#define HAMSTERFILER_VERSION_H

#define HAMSTERFILER_VERSION "@VERSION@"
#define HAMSTERFILER_SEMVER "@VERSION_MAJOR@.@VERSION_MINOR@.@VERSION_REVISION@"

#endif //HAMSTERFILER_VERSION_H
